### ISSUE TITLE
Artisan error

### ISSUE THREAD

**Issue by Messhias** [mjmarianetti/zoho-php#3]
Whe i try do the artisan publish return the error:

  Class 'Mjmarianetti\Zoho\ZohoServiceProvider' not found

**Comment by mjmarianetti** [comment]
@Messhias What was the problem? Sorry I didn't see this before.

**Comment by Messhias** [comment]
I already solved reinstalling all the packages

Em 23/10/2017 14:30, "Martin Marianetti" <notifications@github.com>
escreveu:
